### ISSUE TITLE
Consider consolidation of "custom" azure pipeline files

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_devops#57]
Several repos have pipeline files considered different enough, that they have been broken out into their own directories (in the [.sync/azure_pipelines/custom](https://github.com/microsoft/mu_devops/tree/main/.sync/azure_pipelines/custom) directory of this repo).

The files are maintained in mu_devops so they can be patched with the mu_devops version to use during the file sync process but, are otherwise copied directly to the relevant repo.

> Note that files in [.sync/azure_pipelines/matrix_dependent](https://github.com/microsoft/mu_devops/tree/main/.sync/azure_pipelines/matrix_dependent) already are consolidated across all repos that use a `Matrix-Build-Job<...>.yml` file.

This task is to consider consolidation of the files in "custom" such that the total number of files could be reduced. This could involve content substitution or generation at sync time.

---

I did originally consider doing more to consolidate these files but I felt the tradeoff in complexity of dynamically forming the file versus content reduction made maintainability worse. Looking at the files 1:1 seemed to make it easier to maintain. I'll revisit this in this task though.

**Comment by makubacki** [comment]
Fyi @cfernald & @apop5 

After looking at this, I suggest we keep it as-is. For the following reasons:

1. The files in the "custom" folder are already minimal wrappers. There is diminishing returns in further trying to reduce those files - I basically ended up passing parameters to only pass them as parameters again.
2. Keeping the files in dedicated directories has the advantage that the source history for those files is split per repo making it easy for repo maintainers to easily see their history.
3. Because the files are already reduced, reducing them further begins to introduce complexity that doesn't accomplish much. It's easier to reason about and understand the files if they are not completely dynamically constructed in the sync process but have relatively straightforward substitutions and inclusions (like now).

**Comment by makubacki** [comment]
For reference, here's an example of a common template I made for all pipeline files:

```yaml
{% block copyright %}
## @file
# Azure Pipeline build file for a build using Ubuntu and CLANGPDB.
#
# IMPORTANT: This file requires the local repo to contain a .azurepipelines/Matrix-Build-Job-Clang.yml file that
#            performs the actual build steps for the configurations and packages supported by the repo.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
{% endblock %}

{% block resources %}
{% include 'include/resources.yml' %}
{% endblock %}

{% block variables %}
variables:
{% endblock %}

{% block jobs %}
jobs:
{% endblock %}
```

Individual files could extend this template and override the `variables` and `jobs` sections.

Example:

```yaml
{%extends '../template.yml'}

{% block variables %}
variables:
{% include '../include/var_group/gcc.yml' %}
{% endblock %}

{% block jobs %}
jobs:
- template: Matrix-Build-Job.yml
  parameters:
    arch_list: $(arch_list)
    extra_build_args: CODE_COVERAGE=TRUE CC_HTML=TRUE
    extra_install_step:
    - script: |
              sudo apt-get install -y mingw-w64 lcov
              pip install lcov_cobertura pycobertura
      displayName: Install Windows Resource Compiler for Linux & Code Coverage Tools
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
{% endblock %}
```

The problem is most of the file is the customization in these sections. So, parameterizing this could let to a smaller set of files, but I think it's better to have them broken out to track history per repo.
